// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authorg represents a row from 'dbo.AuthOrg'.
type Authorg struct {
	ID          string    `json:"Id"`          // Id
	Code        string    `json:"Code"`        // Code
	Name        string    `json:"Name"`        // Name
	Fullname    string    `json:"FullName"`    // FullName
	Shortname   string    `json:"ShortName"`   // ShortName
	Sortcode    string    `json:"SortCode"`    // SortCode
	Parentid    string    `json:"ParentId"`    // ParentId
	Level       string    `json:"Level"`       // Level
	Orgtype     string    `json:"OrgType"`     // OrgType
	Leader      string    `json:"Leader"`      // Leader
	Remark      string    `json:"Remark"`      // Remark
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authorg exists in the database.
func (a *Authorg) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authorg has been deleted from the database.
func (a *Authorg) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authorg to the database.
func (a *Authorg) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthOrg (` +
		`Id, Code, Name, FullName, ShortName, SortCode, ParentId, Level, OrgType, Leader, Remark, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Code, a.Name, a.Fullname, a.Shortname, a.Sortcode, a.Parentid, a.Level, a.Orgtype, a.Leader, a.Remark, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Code, a.Name, a.Fullname, a.Shortname, a.Sortcode, a.Parentid, a.Level, a.Orgtype, a.Leader, a.Remark, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authorg in the database.
func (a *Authorg) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthOrg SET ` +
		`Code = $1, Name = $2, FullName = $3, ShortName = $4, SortCode = $5, ParentId = $6, Level = $7, OrgType = $8, Leader = $9, Remark = $10, Revision = $11, CreatedBy = $12, CreatedTime = $13, UpdatedBy = $14, UpdatedTime = $15` +
		` WHERE Id = $16`

	// run query
	XOLog(sqlstr, a.Code, a.Name, a.Fullname, a.Shortname, a.Sortcode, a.Parentid, a.Level, a.Orgtype, a.Leader, a.Remark, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Code, a.Name, a.Fullname, a.Shortname, a.Sortcode, a.Parentid, a.Level, a.Orgtype, a.Leader, a.Remark, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authorg to the database.
func (a *Authorg) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authorg from the database.
func (a *Authorg) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthOrg WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthorgByID retrieves a row from 'dbo.AuthOrg' as a Authorg.
//
// Generated from index 'PK_AuthOrg'.
func AuthorgByID(db XODB, id string) (*Authorg, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, Code, Name, FullName, ShortName, SortCode, ParentId, Level, OrgType, Leader, Remark, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthOrg ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authorg{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Code, &a.Name, &a.Fullname, &a.Shortname, &a.Sortcode, &a.Parentid, &a.Level, &a.Orgtype, &a.Leader, &a.Remark, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
