// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authuserproperty represents a row from 'dbo.AuthUserProperty'.
type Authuserproperty struct {
	ID          string    `json:"Id"`          // Id
	Userid      string    `json:"UserId"`      // UserId
	Name        string    `json:"Name"`        // Name
	Value       string    `json:"Value"`       // Value
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authuserproperty exists in the database.
func (a *Authuserproperty) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authuserproperty has been deleted from the database.
func (a *Authuserproperty) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authuserproperty to the database.
func (a *Authuserproperty) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthUserProperty (` +
		`Id, UserId, Name, Value, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Userid, a.Name, a.Value, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Userid, a.Name, a.Value, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authuserproperty in the database.
func (a *Authuserproperty) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthUserProperty SET ` +
		`UserId = $1, Name = $2, Value = $3, Revision = $4, CreatedBy = $5, CreatedTime = $6, UpdatedBy = $7, UpdatedTime = $8` +
		` WHERE Id = $9`

	// run query
	XOLog(sqlstr, a.Userid, a.Name, a.Value, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Userid, a.Name, a.Value, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authuserproperty to the database.
func (a *Authuserproperty) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authuserproperty from the database.
func (a *Authuserproperty) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthUserProperty WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthuserpropertyByID retrieves a row from 'dbo.AuthUserProperty' as a Authuserproperty.
//
// Generated from index 'PK_AuthUserPeoperty'.
func AuthuserpropertyByID(db XODB, id string) (*Authuserproperty, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, UserId, Name, Value, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthUserProperty ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authuserproperty{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Userid, &a.Name, &a.Value, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
