// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authuserpermit represents a row from 'dbo.AuthUserPermit'.
type Authuserpermit struct {
	ID          string    `json:"Id"`          // Id
	Permitcode  string    `json:"PermitCode"`  // PermitCode
	Userid      string    `json:"UserId"`      // UserId
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authuserpermit exists in the database.
func (a *Authuserpermit) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authuserpermit has been deleted from the database.
func (a *Authuserpermit) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authuserpermit to the database.
func (a *Authuserpermit) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthUserPermit (` +
		`Id, PermitCode, UserId, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Permitcode, a.Userid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Permitcode, a.Userid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authuserpermit in the database.
func (a *Authuserpermit) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthUserPermit SET ` +
		`PermitCode = $1, UserId = $2, Revision = $3, CreatedBy = $4, CreatedTime = $5, UpdatedBy = $6, UpdatedTime = $7` +
		` WHERE Id = $8`

	// run query
	XOLog(sqlstr, a.Permitcode, a.Userid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Permitcode, a.Userid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authuserpermit to the database.
func (a *Authuserpermit) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authuserpermit from the database.
func (a *Authuserpermit) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthUserPermit WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthuserpermitByID retrieves a row from 'dbo.AuthUserPermit' as a Authuserpermit.
//
// Generated from index 'PK_AuthUserPermit'.
func AuthuserpermitByID(db XODB, id string) (*Authuserpermit, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, PermitCode, UserId, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthUserPermit ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authuserpermit{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Permitcode, &a.Userid, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
