// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authuser represents a row from 'dbo.AuthUser'.
type Authuser struct {
	ID          string    `json:"Id"`          // Id
	Code        string    `json:"Code"`        // Code
	Name        string    `json:"Name"`        // Name
	Password    string    `json:"Password"`    // Password
	Salt        string    `json:"Salt"`        // Salt
	Avatar      string    `json:"Avatar"`      // Avatar
	Orgid       string    `json:"OrgId"`       // OrgId
	Email       string    `json:"Email"`       // Email
	Phone       string    `json:"Phone"`       // Phone
	Status      string    `json:"Status"`      // Status
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authuser exists in the database.
func (a *Authuser) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authuser has been deleted from the database.
func (a *Authuser) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authuser to the database.
func (a *Authuser) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthUser (` +
		`Id, Code, Name, Password, Salt, Avatar, OrgId, Email, Phone, Status, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Code, a.Name, a.Password, a.Salt, a.Avatar, a.Orgid, a.Email, a.Phone, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Code, a.Name, a.Password, a.Salt, a.Avatar, a.Orgid, a.Email, a.Phone, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authuser in the database.
func (a *Authuser) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthUser SET ` +
		`Code = $1, Name = $2, Password = $3, Salt = $4, Avatar = $5, OrgId = $6, Email = $7, Phone = $8, Status = $9, Revision = $10, CreatedBy = $11, CreatedTime = $12, UpdatedBy = $13, UpdatedTime = $14` +
		` WHERE Id = $15`

	// run query
	XOLog(sqlstr, a.Code, a.Name, a.Password, a.Salt, a.Avatar, a.Orgid, a.Email, a.Phone, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Code, a.Name, a.Password, a.Salt, a.Avatar, a.Orgid, a.Email, a.Phone, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authuser to the database.
func (a *Authuser) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authuser from the database.
func (a *Authuser) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthUser WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthuserByID retrieves a row from 'dbo.AuthUser' as a Authuser.
//
// Generated from index 'PK_AuthUser'.
func AuthuserByID(db XODB, id string) (*Authuser, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, Code, Name, Password, Salt, Avatar, OrgId, Email, Phone, Status, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthUser ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authuser{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Code, &a.Name, &a.Password, &a.Salt, &a.Avatar, &a.Orgid, &a.Email, &a.Phone, &a.Status, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
