// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authuseraccount represents a row from 'dbo.AuthUserAccount'.
type Authuseraccount struct {
	ID          string    `json:"Id"`          // Id
	Userid      string    `json:"UserId"`      // UserId
	Accountcode string    `json:"AccountCode"` // AccountCode
	Accounttype string    `json:"AccountType"` // AccountType
	Password    string    `json:"Password"`    // Password
	Status      string    `json:"Status"`      // Status
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authuseraccount exists in the database.
func (a *Authuseraccount) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authuseraccount has been deleted from the database.
func (a *Authuseraccount) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authuseraccount to the database.
func (a *Authuseraccount) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthUserAccount (` +
		`Id, UserId, AccountCode, AccountType, Password, Status, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Userid, a.Accountcode, a.Accounttype, a.Password, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Userid, a.Accountcode, a.Accounttype, a.Password, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authuseraccount in the database.
func (a *Authuseraccount) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthUserAccount SET ` +
		`UserId = $1, AccountCode = $2, AccountType = $3, Password = $4, Status = $5, Revision = $6, CreatedBy = $7, CreatedTime = $8, UpdatedBy = $9, UpdatedTime = $10` +
		` WHERE Id = $11`

	// run query
	XOLog(sqlstr, a.Userid, a.Accountcode, a.Accounttype, a.Password, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Userid, a.Accountcode, a.Accounttype, a.Password, a.Status, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authuseraccount to the database.
func (a *Authuseraccount) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authuseraccount from the database.
func (a *Authuseraccount) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthUserAccount WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthuseraccountByID retrieves a row from 'dbo.AuthUserAccount' as a Authuseraccount.
//
// Generated from index 'PK_AuthUserAccount'.
func AuthuseraccountByID(db XODB, id string) (*Authuseraccount, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, UserId, AccountCode, AccountType, Password, Status, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthUserAccount ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authuseraccount{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Userid, &a.Accountcode, &a.Accounttype, &a.Password, &a.Status, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
