// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authrolepermit represents a row from 'dbo.AuthRolePermit'.
type Authrolepermit struct {
	ID          string    `json:"Id"`          // Id
	Permitcode  string    `json:"PermitCode"`  // PermitCode
	Roleid      string    `json:"RoleId"`      // RoleId
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authrolepermit exists in the database.
func (a *Authrolepermit) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authrolepermit has been deleted from the database.
func (a *Authrolepermit) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authrolepermit to the database.
func (a *Authrolepermit) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthRolePermit (` +
		`Id, PermitCode, RoleId, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Permitcode, a.Roleid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Permitcode, a.Roleid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authrolepermit in the database.
func (a *Authrolepermit) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthRolePermit SET ` +
		`PermitCode = $1, RoleId = $2, Revision = $3, CreatedBy = $4, CreatedTime = $5, UpdatedBy = $6, UpdatedTime = $7` +
		` WHERE Id = $8`

	// run query
	XOLog(sqlstr, a.Permitcode, a.Roleid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Permitcode, a.Roleid, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authrolepermit to the database.
func (a *Authrolepermit) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authrolepermit from the database.
func (a *Authrolepermit) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthRolePermit WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthrolepermitByID retrieves a row from 'dbo.AuthRolePermit' as a Authrolepermit.
//
// Generated from index 'PK_AuthRolePermit'.
func AuthrolepermitByID(db XODB, id string) (*Authrolepermit, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, PermitCode, RoleId, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthRolePermit ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authrolepermit{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Permitcode, &a.Roleid, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
