// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Authuserbehavior represents a row from 'dbo.AuthUserBehavior'.
type Authuserbehavior struct {
	ID          string    `json:"Id"`          // Id
	Userid      string    `json:"UserId"`      // UserId
	Objectid    string    `json:"ObjectId"`    // ObjectId
	Objecttype  string    `json:"ObjectType"`  // ObjectType
	Type        string    `json:"Type"`        // Type
	Value       string    `json:"Value"`       // Value
	Memo        string    `json:"Memo"`        // Memo
	Revision    int       `json:"Revision"`    // Revision
	Createdby   string    `json:"CreatedBy"`   // CreatedBy
	Createdtime time.Time `json:"CreatedTime"` // CreatedTime
	Updatedby   string    `json:"UpdatedBy"`   // UpdatedBy
	Updatedtime time.Time `json:"UpdatedTime"` // UpdatedTime

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Authuserbehavior exists in the database.
func (a *Authuserbehavior) Exists() bool {
	return a._exists
}

// Deleted provides information if the Authuserbehavior has been deleted from the database.
func (a *Authuserbehavior) Deleted() bool {
	return a._deleted
}

// Insert inserts the Authuserbehavior to the database.
func (a *Authuserbehavior) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO dbo.AuthUserBehavior (` +
		`Id, UserId, ObjectId, ObjectType, Type, Value, Memo, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12` +
		`)`

	// run query
	XOLog(sqlstr, a.ID, a.Userid, a.Objectid, a.Objecttype, a.Type, a.Value, a.Memo, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	_, err = db.Exec(sqlstr, a.ID, a.Userid, a.Objectid, a.Objecttype, a.Type, a.Value, a.Memo, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime)
	if err != nil {
		return err
	}

	// set existence
	a._exists = true

	return nil
}

// Update updates the Authuserbehavior in the database.
func (a *Authuserbehavior) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE dbo.AuthUserBehavior SET ` +
		`UserId = $1, ObjectId = $2, ObjectType = $3, Type = $4, Value = $5, Memo = $6, Revision = $7, CreatedBy = $8, CreatedTime = $9, UpdatedBy = $10, UpdatedTime = $11` +
		` WHERE Id = $12`

	// run query
	XOLog(sqlstr, a.Userid, a.Objectid, a.Objecttype, a.Type, a.Value, a.Memo, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	_, err = db.Exec(sqlstr, a.Userid, a.Objectid, a.Objecttype, a.Type, a.Value, a.Memo, a.Revision, a.Createdby, a.Createdtime, a.Updatedby, a.Updatedtime, a.ID)
	return err
}

// Save saves the Authuserbehavior to the database.
func (a *Authuserbehavior) Save(db XODB) error {
	if a.Exists() {
		return a.Update(db)
	}

	return a.Insert(db)
}

// Delete deletes the Authuserbehavior from the database.
func (a *Authuserbehavior) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !a._exists {
		return nil
	}

	// if deleted, bail
	if a._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM dbo.AuthUserBehavior WHERE Id = $1`

	// run query
	XOLog(sqlstr, a.ID)
	_, err = db.Exec(sqlstr, a.ID)
	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// AuthuserbehaviorByID retrieves a row from 'dbo.AuthUserBehavior' as a Authuserbehavior.
//
// Generated from index 'PK__AuthUser__3214EC07707F36DB'.
func AuthuserbehaviorByID(db XODB, id string) (*Authuserbehavior, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`Id, UserId, ObjectId, ObjectType, Type, Value, Memo, Revision, CreatedBy, CreatedTime, UpdatedBy, UpdatedTime ` +
		`FROM dbo.AuthUserBehavior ` +
		`WHERE Id = $1`

	// run query
	XOLog(sqlstr, id)
	a := Authuserbehavior{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&a.ID, &a.Userid, &a.Objectid, &a.Objecttype, &a.Type, &a.Value, &a.Memo, &a.Revision, &a.Createdby, &a.Createdtime, &a.Updatedby, &a.Updatedtime)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
