# 后端配置文档,请在修改后另存为`config.yml`

server:
  listenaddr: "" # 监听本地IP 地址; 空字符表示监听所有本地IP
  port: 80 # 监听本地IP 端口号

  ssl: # HTTPS 安全
    enabled: false # 启用
    redirecttohttps: true # 强制跳转HTTPS
    listenaddr: "" # 监听本地IP 地址; 空字符表示监听所有本地IP
    port: 443 # 监听本地IP 端口号
    certfile: # 证书文件 (启用 letsencrypt 不填写)
    certkey: # 证书密钥 (启用 letsencrypt 不填写)
    letsencrypt:
      enabled: false # 启用 letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - mydomain.com
      - myotherdomain.tld
  
  responseheaders: # 输出响应Headers
    Access-Control-Allow-Origin: "*" # 允许跨域的请求限制 http connections
    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # 允许跨域的请求限制 websocket connections (相同域名不受此限制)
      - ".+.example.com"

database: # 连接数据库
  dialect: sqlite3 # 数据库类型
  connection: data/app.db

defaultuser: # 系统默认账号(内置账号)
  name: admin # 用户名
  pass: admin # 密码

uploadedimagesdir: data/images # 上传图片目录
pluginsdir: data/plugins # 插件目录
